-- Asignaturas del Bachillerato en Ciencias (Colegio Esclavas A Coruña)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Matemáticas I (1º Bachillerato)'); -- Bachillerato en Ciencias (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Lengua Castellana y Literatura I (1º Bachillerato)'); -- Bachillerato en Ciencias (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Inglés I (1º Bachillerato)'); -- Bachillerato en Ciencias (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Física y Química I (1º Bachillerato)'); -- Bachillerato en Ciencias (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Biología y Geología (1º Bachillerato)'); -- Bachillerato en Ciencias (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Matemáticas II (2º Bachillerato)'); -- Bachillerato en Ciencias (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Lengua Castellana y Literatura II (2º Bachillerato)'); -- Bachillerato en Ciencias (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Inglés II (2º Bachillerato)'); -- Bachillerato en Ciencias (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Física y Química II (2º Bachillerato)'); -- Bachillerato en Ciencias (2º)
-- Historia (2º Bachillerato) - Omitido en este insert, también presente en el Bachillerato en Humanidades (Colegio La Salle Pontevedra)

-- Asignaturas del Grado en Ingeniería Informática (Colegio Jesuitas A Coruña)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Fundamentos de Programación'); -- Grado en Ingeniería Informática (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Matemáticas para la Computación'); -- Grado en Ingeniería Informática (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Estructuras de Datos'); -- Grado en Ingeniería Informática (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Bases de Datos'); -- Grado en Ingeniería Informática (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Redes de Computadores'); -- Grado en Ingeniería Informática (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Sistemas Operativos'); -- Grado en Ingeniería Informática (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Ingeniería del Software'); -- Grado en Ingeniería Informática (3º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Inteligencia Artificial'); -- Grado en Ingeniería Informática (3º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Programación Web'); -- Grado en Ingeniería Informática (3º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Seguridad Informática'); -- Grado en Ingeniería Informática (4º)

-- Asignaturas del Bachillerato en Humanidades (Colegio La Salle Pontevedra)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Filosofía (1º Bachillerato)'); -- Bachillerato en Humanidades (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Latín (1º Bachillerato)'); -- Bachillerato en Humanidades (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Lengua Castellana y Literatura I (1º Bachillerato)'); -- Bachillerato en Humanidades (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Inglés I (1º Bachillerato)'); -- Bachillerato en Humanidades (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Historia del Mundo Contemporáneo (1º Bachillerato)'); -- Bachillerato en Humanidades (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Literatura Universal (2º Bachillerato)'); -- Bachillerato en Humanidades (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Historia de España (2º Bachillerato)'); -- Bachillerato en Humanidades (2º)
-- Filosofía (2º Bachillerato) - Omitido en este insert, también presente en el Bachillerato en Ciencias (Colegio La Salle Pontevedra)
-- Historia del Arte (2º Bachillerato) - Omitido en este insert, también presente en el Bachillerato en Ciencias (Colegio La Salle Pontevedra)

-- Asignaturas del Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (Colegio La Salle Santiago)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Programación'); -- Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Entornos de Desarrollo'); -- Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Base de Datos'); -- Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Sistemas Informáticos'); -- Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (2º)
-- Lenguajes de Marcas y Sistemas de Gestión de Información (Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online)) - Omitido en este insert, también presente en el Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz)

-- Asignaturas del Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz)
-- Programación (Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz)) - Omitido en este insert, también presente en el Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (Colegio La Salle Santiago)
-- Entornos de Desarrollo (Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz)) - Omitido en este insert, también presente en el Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (Colegio La Salle Santiago)
-- Base de Datos (Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz)) - Omitido en este insert, también presente en el Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (Colegio La Salle Santiago)
-- Sistemas Informáticos (Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz)) - Omitido en este insert, también presente en el Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Online) (Colegio La Salle Santiago)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Lenguajes de Marcas y Sistemas de Gestión de Información'); -- Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz) (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Formación y Orientación Laboral'); -- Técnico Superior en Desarrollo de Aplicaciones Multiplataforma (Colegio Liceo La Paz) (2º)

-- Asignaturas del Técnico en Cocina y Gastronomía (Presencial) (Colegio Maristas Lugo)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Operaciones Básicas de Cocina'); -- Técnico en Cocina y Gastronomía (Presencial) (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Elaboraciones Básicas de Repostería y Pastelería'); -- Técnico en Cocina y Gastronomía (Presencial) (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Gestión Administrativa y Comercial en Restauración'); -- Técnico en Cocina y Gastronomía (Presencial) (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Ofertas Gastronómicas'); -- Técnico en Cocina y Gastronomía (Presencial) (2º)
-- Inglés (Técnico en Cocina y Gastronomía (Presencial)) - Omitido en este insert, también presente en el Técnico en Cocina y Gastronomía (Presencial) (Colegio Santa Teresa de Jesús Ourense)
-- Formación y Orientación Laboral (Técnico en Cocina y Gastronomía (Presencial)) - Omitido en este insert, también presente en el Técnico en Cocina y Gastronomía (Presencial) (Colegio Santa Teresa de Jesús Ourense)

-- Asignaturas del Desarrollo de Aplicaciones Web (Colegio San Clemente)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Programación en Entorno Cliente'); -- Desarrollo de Aplicaciones Web (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Programación en Entorno Servidor'); -- Desarrollo de Aplicaciones Web (1º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Despliegue de Aplicaciones Web'); -- Desarrollo de Aplicaciones Web (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Diseño de Interfaces Web'); -- Desarrollo de Aplicaciones Web (2º)
INSERT INTO PUBLIC."Subject" ("name") 
VALUES ('Empresa e Iniciativa Emprendedora'); -- Desarrollo de Aplicaciones Web (2º)
-- Formación en Centros de Trabajo (Desarrollo de Aplicaciones Web) - Omitido en este insert, también presente en el Técnico en Pastelería, Repostería y Panadería (Colegio San Clemente)
